name: publish
run-name: ${{ github.actor }} is publishing a new version
on:
  push:
    branches:
      - master
      - main
      - initial

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Webpack Build
        id: webpack_build
        shell: bash
        run: |
          npm install
          npm run build

      - name: Compile server
        id: compile_server
        run: npm run compile

      - name: Build pages
        run: npm run serve & npm run generate

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: curtis-rochelle-build-artifacts
          path: public/

  publish:
    runs-on: ubuntu-latest
    needs:
      - compile
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.pre_release_name }}
          path: ${{ runner.temp }}/public

      - name: Create tarball
        run: tar -czvf ${{ runner.temp }}/curtis-rochelle-build-artifacts.tar.gz ${{ runner.temp }}/public

      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.pre_release_name }}
          path: ${{ runner.temp }}/curtis-rochelle-build-artifacts.tar.gz
          retention-days: 5
          if-no-files-found: error
